Grabbag
Rainchus/mp1 pull request #13
Opened 2022-11-27 03:13 UTC by M0liusX

2022-11-27 04:29 UTC, Rainchus requested changes

2022-11-27 04:29 UTC, Rainchus commented on src/ovl_1C_GrabBag/1837D0.h
> +void func_800F6C98_183E88();
For functions that take no args, you should include `void` in the signature. If the args are left blank it means the function takes a variable amount of args

2022-11-27 04:29 UTC, Rainchus commented on src/ovl_1C_GrabBag/1837D0.c
> +    temp_s1 = temp_v0 & 0xFF;
Generally you wont have to manually & a variable like this unless it's flag/bits related. It should be possible to only use temp_s1 or temp_v0 for all of these function calls and then make sure the signatures of the functions are correct ( https://decomp.me/scratch/5zvoJ )

2022-11-28 00:17 UTC, M0liusX commented
Fixed as per Rainchus' comments!

2022-11-30 22:02 UTC, merged